version: ~> 1.0
os: linux
dist: bionic
language: node_js
install:
  - npm ci
script:
  - npm run build
  - npm run test
  # List the published package’s content.
  - npm pack --loglevel notice 2>&1 >/dev/null | sed -e 's/^npm notice //' && rm *.tgz
notifications:
  email: false
